gitlab-ci: Finish check_container_template fully before claiming a failed test case
The .check_container_template test case checks whether all
packages were successfully installed into container images. The
test bails out early due to 'exit 1' in each error path. This is
suboptimal and when fixing missing packages multiple iterations
of CI runs are needed.

In case of failed test case, just store this flag internally and
propagate error after all test cases have run.

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -85,6 +85,7 @@ stages:
   script:
     - source <(_venv_/bin/python3 bin/lcitool -d /tmp/datadir variables $NAME all_mappings | grep PKGS)
     - set +e
+    - ret=0
     - for pkg in $PKGS;
       do
         echo -n "Checking package '$pkg' ... ";
@@ -97,7 +98,7 @@ stages:
           echo "LAST ERROR:";
           echo "-----------";
           echo -e "$out";
-          exit 1;
+          ret=1;
         fi;
       done
 
@@ -113,7 +114,7 @@ stages:
           echo "LAST ERROR:";
           echo "-----------";
           echo -e "$out";
-          exit 1;
+          ret=1;
         fi;
       done
 
@@ -129,9 +130,16 @@ stages:
           echo "LAST ERROR:";
           echo "-----------";
           echo -e "$out";
-          exit 1;
+          ret=1;
         fi;
       done
+
+    - if [ $ret -ne 0 ];
+      then
+        echo "Some failures occurred. See above";
+        exit $ret;
+      fi;
+
   variables:
     CPAN_DRY_RUN_COMMAND: cpanm --scandeps
   rules:
