.gitlab-ci: Properly test installation of all mappings
This patch reworks the all package installation job so that it actually
tries to install every single mapping we know of on most platforms as
opposed to just merge all projects we currently "maintain" and install
those packages in a single transaction. The obvious problems are:
    - some mappings are never exercised
    - some mappings can actually conflict on a given platform

This patch fixes the above by installing every single of our mappings
(including Python and Perl ones) individually in a dry-run manner so
that we don't waste resources on downloading the packages and writing
to the disk.
There are a few pitfalls though required and ugly solution:
    - for DNF we need to use a wrapper script because DNF doesn't
      implement a proper dry-run install
    - Alpine implements wget in Busybox which cpanm relies on and on
      3.15 it's missing some CLI option so we need to use '--no-wget'
      with cpanm; on 3.16 wget still doesn't implement the option, but
      this one actually works with the defaults and doesn't work at all
      when combined with the '--no-wget' option (it's a mess!)
    - OpenSUSE doesn't create the python3 symlink automatically, it
      only does that with 3.6, so 'update-alternatives' had to be used
      to actually use a more modern Python (lcitool needs >=3.8)
    - all Python installs are happening in a virtual env because Debian
      decided to block pip from installing to system locations

Signed-off-by: Erik Skultety <eskultet@redhat.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -68,18 +68,72 @@ stages:
 
 .check_container_template:
   extends: .test_template
-  image: docker:stable
+  image: $IMAGE
   stage: sanity_checks
   interruptible: true
-  services:
-    - docker:dind
   before_script:
-    - docker info
-    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
+    - ci/gitlab/all_mappings_prep_env/$NAME-prep.sh
+    - mkdir -p /tmp/datadir/projects
+    - cp tests/data/packages/in/packages.yml /tmp/datadir/projects/all_mappings.yml
+
+    # We need to use Python virtual env because some platforms have an old
+    # version of pip that does not have the '--dry-run' option and because
+    # installing to system locations is broken on Debian
+    - python3 -m venv _venv_
+    - _venv_/bin/pip3 install --upgrade pip
+    - _venv_/bin/python3 -m pip install -r requirements.txt
   script:
-    - docker build -f tests/data/formatters/out/${NAME}-all-projects.Dockerfile tests/data/formatters/out/
-  after_script:
-    - docker logout
+    - source <(_venv_/bin/python3 bin/lcitool -d /tmp/datadir variables $NAME all_mappings | grep PKGS)
+    - set +e
+    - for pkg in $PKGS;
+      do
+        echo -n "Checking package '$pkg' ... ";
+        out=$($DRY_RUN_INSTALL_COMMAND $pkg 2>&1);
+        if [ $? -eq 0 ];
+        then
+          echo "OK";
+        else
+          echo "FAIL";
+          echo "LAST ERROR:";
+          echo "-----------";
+          echo -e "$out";
+          exit 1;
+        fi;
+      done
+
+    - for pkg in $PYPI_PKGS;
+      do
+        echo -n "Checking PyPI package '$pkg' ... ";
+        out=$(_venv_/bin/python3 -m pip install --dry-run $pkg 2>&1);
+        if [ $? -eq 0 ];
+        then
+          echo "OK";
+        else
+          echo "FAIL";
+          echo "LAST ERROR:";
+          echo "-----------";
+          echo -e "$out";
+          exit 1;
+        fi;
+      done
+
+    - for pkg in $CPAN_PKGS;
+      do
+        echo -n "Checking CPAN package '$pkg' ... ";
+        out=$($CPAN_DRY_RUN_COMMAND $pkg 2>&1);
+        if [ $? -eq 0 ];
+        then
+          echo "OK";
+        else
+          echo "FAIL";
+          echo "LAST ERROR:";
+          echo "-----------";
+          echo -e "$out";
+          exit 1;
+        fi;
+      done
+  variables:
+    CPAN_DRY_RUN_COMMAND: cpanm --scandeps
   rules:
     - if: '$LIBVIRT_CI_SKIP_TARGET && $NAME =~ $LIBVIRT_CI_SKIP_TARGET'
       when: never
@@ -163,92 +217,144 @@ unittests:
   script:
     - tox -e py38
 
+# DNF returns 1 when 'install --assumeno' is used which is undistinguishable
+# from genuine errors, let's install our DNF helper that checks whether the
+# failure just means that the installation was aborted or whether the package
+# actually doesn't exist
+.dnf_dry_run_command: &dnf_dry_run_command
+    DRY_RUN_INSTALL_COMMAND: ci/gitlab/all_mappings_prep_env/dnf_install_wrapper install --assumeno
+
+.apt_dry_run_command: &apt_dry_run_command
+  DRY_RUN_INSTALL_COMMAND: apt --dry-run install
+
+.apk_dry_run_command: &apk_dry_run_command
+  DRY_RUN_INSTALL_COMMAND: apk add -s
+
+.zypper_dry_run_command: &zypper_dry_run_command
+  DRY_RUN_INSTALL_COMMAND: zypper install -y --dry-run
+
 x86_64-check-almalinux-8:
   extends: .check_container_template
   variables:
+    <<: *dnf_dry_run_command
+    IMAGE: docker.io/library/almalinux:8
     NAME: almalinux-8
 
 x86_64-check-almalinux-9:
   extends: .check_container_template
   variables:
+    <<: *dnf_dry_run_command
+    IMAGE: docker.io/library/almalinux:9
     NAME: almalinux-9
 
 x86_64-check-alpine-315:
   extends: .check_container_template
   variables:
+    <<: *apk_dry_run_command
+    IMAGE: docker.io/library/alpine:3.15
     NAME: alpine-315
+    # wget on Alpine is implemented in Busybox and doesn't have all options
+    CPAN_DRY_RUN_COMMAND: cpanm --scandeps --no-wget
 
 x86_64-check-alpine-316:
   extends: .check_container_template
   variables:
+    <<: *apk_dry_run_command
+    IMAGE: docker.io/library/alpine:3.16
     NAME: alpine-316
 
 x86_64-check-alpine-edge:
   extends: .check_container_template
   allow_failure: true
   variables:
+    <<: *apk_dry_run_command
+    IMAGE: docker.io/library/alpine:edge
     NAME: alpine-edge
 
 x86_64-check-centos-stream-8:
   extends: .check_container_template
   variables:
+    <<: *dnf_dry_run_command
+    IMAGE: quay.io/centos/centos:stream8
     NAME: centos-stream-8
 
 x86_64-check-centos-stream-9:
   extends: .check_container_template
   allow_failure: true
   variables:
+    <<: *dnf_dry_run_command
+    IMAGE: quay.io/centos/centos:stream9
     NAME: centos-stream-9
 
 x86_64-check-debian-10:
   extends: .check_container_template
   variables:
+    <<: *apt_dry_run_command
+    IMAGE: docker.io/library/debian:10-slim
     NAME: debian-10
 
 x86_64-check-debian-11:
   extends: .check_container_template
   variables:
+    <<: *apt_dry_run_command
+    IMAGE: docker.io/library/debian:11-slim
     NAME: debian-11
 
 x86_64-check-debian-sid:
   extends: .check_container_template
   allow_failure: true
   variables:
+    <<: *apt_dry_run_command
+    IMAGE: docker.io/library/debian:sid-slim
     NAME: debian-sid
 
 x86_64-check-fedora-37:
   extends: .check_container_template
   variables:
+    <<: *dnf_dry_run_command
+    IMAGE: registry.fedoraproject.org/fedora:38
     NAME: fedora-37
 
 x86_64-check-fedora-38:
   extends: .check_container_template
   variables:
+    <<: *dnf_dry_run_command
+    IMAGE: registry.fedoraproject.org/fedora:37
     NAME: fedora-38
 
 x86_64-check-fedora-rawhide:
   extends: .check_container_template
   allow_failure: true
   variables:
+    <<: *dnf_dry_run_command
+    IMAGE: registry.fedoraproject.org/fedora:rawhide
     NAME: fedora-rawhide
 
 x86_64-check-opensuse-leap-15:
   extends: .check_container_template
   variables:
+    <<: *zypper_dry_run_command
+    IMAGE: registry.opensuse.org/opensuse/leap:15.4
     NAME: opensuse-leap-15
 
 x86_64-check-opensuse-tumbleweed:
   extends: .check_container_template
   allow_failure: true
   variables:
+    <<: *zypper_dry_run_command
+    IMAGE: registry.opensuse.org/opensuse/tumbleweed:latest
     NAME: opensuse-tumbleweed
 
 x86_64-check-ubuntu-2004:
   extends: .check_container_template
   variables:
+    <<: *apt_dry_run_command
+    IMAGE: docker.io/library/ubuntu:20.04
     NAME: ubuntu-2004
 
 x86_64-check-ubuntu-2204:
   extends: .check_container_template
   variables:
+    <<: *apt_dry_run_command
+    IMAGE: docker.io/library/ubuntu:22.04
     NAME: ubuntu-2204
